In [121]:
import numpy as np
from matplotlib import pyplot as plt 
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#np array
b = np.arange(4) #creat 0-4 array
c = np.zeros((5,7))# 5row 7col zero martix
print(a)
print(b)
print(b<=2)
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[0 1 2 3]
[ True  True  True False]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [122]:
b = b.reshape(2,2)# reshape 2 col 2 row
print(b)

[[0 1]
 [2 3]]


In [123]:
a = np.array([[32,99],[23,77],[12,20]])
c = np.dot(a,b)#dot product
c_2 = a.dot(b)
print(c)
print(c_2)

[[198 329]
 [154 254]
 [ 40  72]]
[[198 329]
 [154 254]
 [ 40  72]]


In [124]:
a = np.random.random((2,4))# random array 2 raw 4 col
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))

[[0.63261625 0.41697791 0.50881854 0.61037139]
 [0.45816208 0.90747231 0.81509723 0.79413896]]
5.143654675336126
0.9074723112854812
0.416977914158132


In [125]:
# numpy的索引和运算
a = np.random.random((3,4))
print(a)
print(np.argmin(a,axis = 0))#每一列最小值的索引
print(np.argmax(a,axis = 1))#每一行最大值的索引
print(np.sort(a))
print(np.transpose(a))#T
print(np.cumsum(a))#累加
print(np.diff(a))#差
print(np.clip(a,0.2,0.5))#截取片段，0.2<x<0.5，如果大于0.5，则等于0.5。如果小于0.2，则等于0.2

[[0.68720618 0.38093594 0.05023709 0.62500435]
 [0.95965036 0.69335375 0.96702767 0.244304  ]
 [0.73946418 0.46340468 0.03929843 0.97249464]]
[0 0 2 1]
[0 2 3]
[[0.05023709 0.38093594 0.62500435 0.68720618]
 [0.244304   0.69335375 0.95965036 0.96702767]
 [0.03929843 0.46340468 0.73946418 0.97249464]]
[[0.68720618 0.95965036 0.73946418]
 [0.38093594 0.69335375 0.46340468]
 [0.05023709 0.96702767 0.03929843]
 [0.62500435 0.244304   0.97249464]]
[0.68720618 1.06814213 1.11837921 1.74338357 2.70303393 3.39638768
 4.36341535 4.60771934 5.34718352 5.8105882  5.84988663 6.82238126]
[[-0.30627024 -0.33069886  0.57476727]
 [-0.26629661  0.27367391 -0.72272367]
 [-0.2760595  -0.42410625  0.93319621]]
[[0.5        0.38093594 0.2        0.5       ]
 [0.5        0.5        0.5        0.244304  ]
 [0.5        0.46340468 0.2        0.5       ]]


In [126]:
#numpy array的合并

a = np.array([1,1,1])
b = np.array([2,2,2])
print(a)
print(b)
print(np.vstack((a,b))) # vertical stack

#a变成纵向列表
#print(a[np.newaxis,:]) 在行上加维度
print(a[:,np.newaxis]) #在列上加维度
print(a.shape)

#a,b变为纵向列表
a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
c = np.concatenate((a,b,b,a),axis=1)#多重合并，axis=0为vertical axis=1为horizontal
print(np.hstack((a,b))) # horizontal stack
print(c)


[1 1 1]
[2 2 2]
[[1 1 1]
 [2 2 2]]
[[1]
 [1]
 [1]]
(3,)
[[1 2]
 [1 2]
 [1 2]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [127]:
#numpy array的分割
a = np.arange(12)
a = a.reshape((3,4))
print(a)
#横向分割
print(np.split(a,3,axis=0))#axis=0 对row进行操作
#纵向分割
print(np.split(a,4,axis=1))#axis=1 对col进行操作，分成4份
print(np.split(a,2,axis=1))#分成2份

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [128]:
# array data type转换
a = np.arange(4)
print(a.dtype)
float_a = a.astype(np.float64)
print(float_a.dtype)
#字符串转float或者int
string=np.array(['1.1','-9.6','7'],dtype=np.string_)
print(string.dtype)
string_float = string.astype(np.float64)
print(string_float)
print(string_float.dtype) # string不能直接转船int，先转换float 再int
string_int = string_float.astype(np.int)
print(string_int.dtype)


int64
float64
|S4
[ 1.1 -9.6  7. ]
float64
int64


In [129]:
#array切片
a = np.arange(10)
print(a)
a[4:8] = 12 #第4-8个元素赋值12
#提取第4-8个元素
a_slice = a[4:8]
print(a_slice)
a_slice[1] = 121212
print(a_slice)
print(a) #?????为什么a_slice会直接赋值给a

#2d提取
b = np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array
print(b)
print(b[2])
print(b[2][0])#b第三行的第一列元素
print(b[2,0])#同上

a_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3d array 2x2x3
print(a_3d)
print(a_3d[0])#一个2x3的matrix
k = (a_3d[0]*2).copy()
a_3d[0] = k #替换a_3d第一个元素成k
print(k)
print(a_3d)
print(a_3d[0,1,1])#从3d matrix提取单个元素

[0 1 2 3 4 5 6 7 8 9]
[12 12 12 12]
[    12 121212     12     12]
[     0      1      2      3     12 121212     12     12      8      9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
7
7
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[[ 2  4  6]
  [ 8 10 12]]

 [[ 7  8  9]
  [10 11 12]]]
10


In [130]:
#array索引
a = np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array
print(a[:2]) #提取0，1个元素，不包括2
print(a[:2,:1])#提取0，1元素中的第0个数值（不包括1）
print(a[:2,1:])#提取0，1元素中的第2个数值开始的所有数值
print(a[:,1:])#只有：代表取整个轴

names = np.array(['Bob','Joe','Will','Bob','Joe','Joe','Will'])
data = np.random.random((7,4))
print(data)
print(names=='Bob')
print(data[names == 'Bob'])#选中bob对应的所有数据
print(data[names == 'Bob',2:])#选中bob对应的数据中第2个后所有数据
print(names!='Bob')#除了bob，其他人的数据
names2 = (names=='Bob') | (names=='Will')#选中bob和will
print(names2)
print(data[names2])
data[names!='Joe']=0 #塞选出仅joe的data，除了joe的data 其他全部设置为0
print(data)

[[1 2 3]
 [4 5 6]]
[[1]
 [4]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[0.11910202 0.07706152 0.81283717 0.98388262]
 [0.29907124 0.73641334 0.61482818 0.70084986]
 [0.10204433 0.79312652 0.50055289 0.10564125]
 [0.90797958 0.65890874 0.06483621 0.36652233]
 [0.67053809 0.60425979 0.28428349 0.32654027]
 [0.66755963 0.01902619 0.74049894 0.05876903]
 [0.13314078 0.6279655  0.28560593 0.91480548]]
[ True False False  True False False False]
[[0.11910202 0.07706152 0.81283717 0.98388262]
 [0.90797958 0.65890874 0.06483621 0.36652233]]
[[0.81283717 0.98388262]
 [0.06483621 0.36652233]]
[False  True  True False  True  True  True]
[ True False  True  True False False  True]
[[0.11910202 0.07706152 0.81283717 0.98388262]
 [0.10204433 0.79312652 0.50055289 0.10564125]
 [0.90797958 0.65890874 0.06483621 0.36652233]
 [0.13314078 0.6279655  0.28560593 0.91480548]]
[[0.         0.         0.         0.        ]
 [0.29907124 0.73641334 0.61482818 0.70084986]
 [0.         0.         0.         0.     

In [155]:
#Fancy Indexing
a = np.zeros((8,4))
for i in range(8):
    a[i] = i
print(a)
print(a[[4,2,7,1]])#提取特定的子序列，用整数表示即可
print(a[[-1,-2,-3]])#从末尾开始提取
b = np.arange(32)
b = b.reshape((8,4))
print(b)
print(b[[1,3,5,7],[0,1,2,3]])#从b中的1，3，5，7个元素中，分别提取第0，1，2，3个数值
print(b[[1,2,3,4]][:,[3,2,1,0]])#取b中1，2，3，4个元素的所有列，然后给予没个位置赋值，顺序为数列中的数值位的[3,2,1,0]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [2. 2. 2. 2.]
 [7. 7. 7. 7.]
 [1. 1. 1. 1.]]
[[7. 7. 7. 7.]
 [6. 6. 6. 6.]
 [5. 5. 5. 5.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 13 22 31]
[[ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]
 [19 18 17 16]]
