In [63]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#np array
b = np.arange(4) #creat 0-4 array
c = np.zeros((5,7))# 5row 7col zero martix
print(a)
print(b)
print(b<=2)
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[0 1 2 3]
[ True  True  True False]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [64]:
b = b.reshape(2,2)# reshape 2 col 2 row
print(b)

[[0 1]
 [2 3]]


In [65]:
a = np.array([[32,99],[23,77],[12,20]])
c = np.dot(a,b)#dot product
c_2 = a.dot(b)
print(c)
print(c_2)

[[198 329]
 [154 254]
 [ 40  72]]
[[198 329]
 [154 254]
 [ 40  72]]


In [66]:
a = np.random.random((2,4))# random array 2 raw 4 col
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))

[[0.0427342  0.03470798 0.43847642 0.10401154]
 [0.69274545 0.50973915 0.55550272 0.88907502]]
3.2669924823483294
0.889075017373585
0.03470798123785568


In [67]:
# numpy的索引和运算
a = np.random.random((3,4))
print(a)
print(np.argmin(a,axis = 0))#每一列最小值的索引
print(np.argmax(a,axis = 1))#每一行最大值的索引
print(np.sort(a))
print(np.transpose(a))#T
print(np.cumsum(a))#累加
print(np.diff(a))#差
print(np.clip(a,0.2,0.5))#截取片段，0.2<x<0.5，如果大于0.5，则等于0.5。如果小于0.2，则等于0.2

[[0.77242799 0.87646778 0.07635367 0.59965244]
 [0.58180146 0.53924247 0.70233722 0.83488296]
 [0.26148956 0.10232897 0.09448873 0.66664858]]
[2 2 0 0]
[1 3 3]
[[0.07635367 0.59965244 0.77242799 0.87646778]
 [0.53924247 0.58180146 0.70233722 0.83488296]
 [0.09448873 0.10232897 0.26148956 0.66664858]]
[[0.77242799 0.58180146 0.26148956]
 [0.87646778 0.53924247 0.10232897]
 [0.07635367 0.70233722 0.09448873]
 [0.59965244 0.83488296 0.66664858]]
[0.77242799 1.64889577 1.72524944 2.32490188 2.90670334 3.44594581
 4.14828303 4.98316599 5.24465555 5.34698452 5.44147326 6.10812184]
[[ 0.10403979 -0.8001141   0.52329876]
 [-0.04255899  0.16309475  0.13254574]
 [-0.15916059 -0.00784024  0.57215985]]
[[0.5        0.5        0.2        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.26148956 0.2        0.2        0.5       ]]


In [88]:
#numpy array的合并

a = np.array([1,1,1])
b = np.array([2,2,2])
print(a)
print(b)
print(np.vstack((a,b))) # vertical stack

#a变成纵向列表
#print(a[np.newaxis,:]) 在行上加维度
print(a[:,np.newaxis]) #在列上加维度
print(a.shape)

#a,b变为纵向列表
a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
c = np.concatenate((a,b,b,a),axis=1)#多重合并，axis=0为vertical axis=1为horizontal
print(np.hstack((a,b))) # horizontal stack
print(c)


[1 1 1]
[2 2 2]
[[1 1 1]
 [2 2 2]]
[[1]
 [1]
 [1]]
(3,)
[[1 2]
 [1 2]
 [1 2]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [98]:
#numpy array的分割
a = np.arange(12)
a = a.reshape((3,4))
print(a)
#横向分割
print(np.split(a,3,axis=0))#axis=0 对row进行操作
#纵向分割
print(np.split(a,4,axis=1))#axis=1 对col进行操作，分成4份
print(np.split(a,2,axis=1))#分成2份

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
